spring:
  profiles:
    active: dev
---
################# development environment #################
spring:
  profiles: dev
  datasource:
#      type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
#      username: root
#      password: root
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
        username: root
        password: root
      slaver:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
        username: root
        password: root

server:
  port: 8166
---
################# test environment #################
spring:
  profiles: test
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
      username: root
      password: root

server:
  port: 8186
---
################# production environment #################
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: root

server:
  port: 8196

